#if !defined(AFX_ITHERMOMETERX_H__DE87C81E_9774_43EF_BB37_1F3FF02A3A82__INCLUDED_)
#define AFX_ITHERMOMETERX_H__DE87C81E_9774_43EF_BB37_1F3FF02A3A82__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;
class CPicture;

/////////////////////////////////////////////////////////////////////////////
// CiThermometerX wrapper class

class CiThermometerX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CiThermometerX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xc5412df6, 0x2e2f, 0x11d3, { 0x85, 0xbf, 0x0, 0x10, 0x5a, 0xc8, 0xb7, 0x15 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long GetIndicatorWidth();
	void SetIndicatorWidth(long nNewValue);
	long GetIndicatorBulbSize();
	void SetIndicatorBulbSize(long nNewValue);
	long GetEndsMargin();
	void SetEndsMargin(long nNewValue);
	unsigned long GetIndicatorColor();
	void SetIndicatorColor(unsigned long newValue);
	unsigned long GetIndicatorBackGroundColor();
	void SetIndicatorBackGroundColor(unsigned long newValue);
	long GetOrientation();
	void SetOrientation(long nNewValue);
	long GetOrientationTickMarks();
	void SetOrientationTickMarks(long nNewValue);
	BOOL GetShowTicksMajorFirstLast();
	void SetShowTicksMajorFirstLast(BOOL bNewValue);
	unsigned long GetBackGroundColor();
	void SetBackGroundColor(unsigned long newValue);
	long GetBorderStyle();
	void SetBorderStyle(long nNewValue);
	BOOL GetShowMaxPointer();
	void SetShowMaxPointer(BOOL bNewValue);
	BOOL GetShowMinPointer();
	void SetShowMinPointer(BOOL bNewValue);
	long GetMinMaxPointerSize();
	void SetMinMaxPointerSize(long nNewValue);
	long GetMinMaxPointerMargin();
	void SetMinMaxPointerMargin(long nNewValue);
	unsigned long GetMaxPointerColor();
	void SetMaxPointerColor(unsigned long newValue);
	unsigned long GetMinPointerColor();
	void SetMinPointerColor(unsigned long newValue);
	long GetOffsetX();
	void SetOffsetX(long nNewValue);
	long GetOffsetY();
	void SetOffsetY(long nNewValue);
	long GetTickMajorStyle();
	void SetTickMajorStyle(long nNewValue);
	long GetTickMinorStyle();
	void SetTickMinorStyle(long nNewValue);
	BOOL GetShowTicksMajor();
	void SetShowTicksMajor(BOOL bNewValue);
	BOOL GetShowTicksMinor();
	void SetShowTicksMinor(BOOL bNewValue);
	BOOL GetShowTickLabels();
	void SetShowTickLabels(BOOL bNewValue);
	long GetTickMajorCount();
	void SetTickMajorCount(long nNewValue);
	unsigned long GetTickMajorColor();
	void SetTickMajorColor(unsigned long newValue);
	long GetTickMajorLength();
	void SetTickMajorLength(long nNewValue);
	long GetTickMinorAlignment();
	void SetTickMinorAlignment(long nNewValue);
	long GetTickMinorCount();
	void SetTickMinorCount(long nNewValue);
	unsigned long GetTickMinorColor();
	void SetTickMinorColor(unsigned long newValue);
	long GetTickMinorLength();
	void SetTickMinorLength(long nNewValue);
	long GetTickMargin();
	void SetTickMargin(long nNewValue);
	long GetTickLabelMargin();
	void SetTickLabelMargin(long nNewValue);
	COleFont GetTickLabelFont();
	void SetTickLabelFont(LPDISPATCH newValue);
	long GetTickLabelPrecision();
	void SetTickLabelPrecision(long nNewValue);
	void ResetMinMax();
	double GetCurrentMax();
	void SetCurrentMax(double newValue);
	double GetCurrentMin();
	void SetCurrentMin(double newValue);
	double GetPositionPercent();
	void SetPositionPercent(double newValue);
	double GetPosition();
	void SetPosition(double newValue);
	double GetPositionMax();
	void SetPositionMax(double newValue);
	double GetPositionMin();
	void SetPositionMin(double newValue);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	void AboutBox();
	unsigned long GetTickLabelFontColor();
	void SetTickLabelFontColor(unsigned long newValue);
	CPicture GetBackGroundPicture();
	void SetBackGroundPicture(LPDISPATCH newValue);
	void ShowPropertyEditor();
	void SetPositionNoEvent(double Value);
	BOOL GetMinMaxFixed();
	void SetMinMaxFixed(BOOL bNewValue);
	BOOL GetMinMaxUserCanMove();
	void SetMinMaxUserCanMove(BOOL bNewValue);
	long GetIndicatorStyle();
	void SetIndicatorStyle(long nNewValue);
	BOOL GetTransparent();
	void SetTransparent(BOOL bNewValue);
	void AddLimit(long PointerSize, long PointerMargin, BOOL DrawScaleSide, double UpperValue, double LowerValue, unsigned long UpperPointerColor, unsigned long LowerPointerColor);
	void RemoveLimit(long Index);
	void RemoveAllLimits();
	double GetLimitUpperValue(long Index);
	double GetLimitLowerValue(long Index);
	long GetLimitPointerSize(long Index);
	long GetLimitPointerMargin(long Index);
	unsigned long GetLimitUpperPointerColor(long Index);
	BOOL GetLimitShowUpperPointer(long Index);
	BOOL GetLimitDrawScaleSide(long Index);
	long GetLimitCount();
	void SetLimitUpperValue(long Index, double Value);
	void SetLimitLowerValue(long Index, double Value);
	void SetLimitPointerSize(long Index, long Value);
	void SetLimitPointerMargin(long Index, long Value);
	void SetLimitUpperPointerColor(long Index, unsigned long Value);
	void SetLimitShowUpperPointer(long Index, BOOL Value);
	void SetLimitDrawScaleSide(long Index, BOOL Value);
	void RepaintAll();
	BOOL GetAutoCenter();
	void SetAutoCenter(BOOL bNewValue);
	unsigned long GetLimitLowerPointerColor(long Index);
	BOOL GetLimitShowLowerPointer(long Index);
	void SetLimitLowerPointerColor(long Index, unsigned long Value);
	void SetLimitShowLowerPointer(long Index, BOOL Value);
	long GetPrecisionStyle();
	void SetPrecisionStyle(long nNewValue);
	void BeginUpdate();
	void EndUpdate();
	long GetAutoScaleDesiredTicks();
	void SetAutoScaleDesiredTicks(long nNewValue);
	long GetAutoScaleMaxTicks();
	void SetAutoScaleMaxTicks(long nNewValue);
	BOOL GetAutoScaleEnabled();
	void SetAutoScaleEnabled(BOOL bNewValue);
	long GetAutoScaleStyle();
	void SetAutoScaleStyle(long nNewValue);
	void Lock();
	void Unlock();
	long GetUpdateFrameRate();
	void SetUpdateFrameRate(long nNewValue);
	long GetComponentHandle();
	void SaveImageToBitmap(LPCTSTR FileName);
	void SaveImageToMetaFile(LPCTSTR FileName);
	void SaveImageToJPEG(LPCTSTR FileName, long Compression, BOOL Progressive);
	long OPCAddItem();
	long OPCItemCount();
	void OPCRemoveAllItems();
	void OPCItemActivate(long Index);
	void OPCItemDeactivate(long Index);
	CString GetOPCItemComputerName(long Index);
	CString GetOPCItemServerName(long Index);
	CString GetOPCItemItemName(long Index);
	CString GetOPCItemPropertyName(long Index);
	BOOL GetOPCItemAutoConnect(long Index);
	long GetOPCItemUpdateRate(long Index);
	void SetOPCItemComputerName(long Index, LPCTSTR Value);
	void SetOPCItemServerName(long Index, LPCTSTR Value);
	void SetOPCItemItemName(long Index, LPCTSTR Value);
	void SetOPCItemPropertyName(long Index, LPCTSTR Value);
	void SetOPCItemAutoConnect(long Index, BOOL Value);
	void SetOPCItemUpdateRate(long Index, long Value);
	void OPCItemLoaded(long Index);
	BOOL GetCachedDrawing();
	void SetCachedDrawing(BOOL bNewValue);
	long GetObjectPointer();
	VARIANT GetBytesJPEG(long Compression, BOOL Progressive);
	void SavePropertiesToFile(LPCTSTR FileName);
	void LoadPropertiesFromFile(LPCTSTR FileName);
	BOOL GetReverseScale();
	void SetReverseScale(BOOL bNewValue);
	long GetIndicatorFillReferenceStyle();
	void SetIndicatorFillReferenceStyle(long nNewValue);
	double GetIndicatorFillReferenceValue();
	void SetIndicatorFillReferenceValue(double newValue);
	BOOL GetOptionSaveAllProperties();
	void SetOptionSaveAllProperties(BOOL bNewValue);
	BOOL GetAutoFrameRate();
	void SetAutoFrameRate(BOOL bNewValue);
	void iPaintToDC(long X, long Y, BOOL Transparent, long DC);
	long GetWidth();
	void SetWidth(long nNewValue);
	long GetHeight();
	void SetHeight(long nNewValue);
	void OPCItemUpdateResume(long Index);
	void OPCItemUpdateSuspend(long Index);
	VARIANT GetOPCItemData(long Index);
	short GetOPCItemQuality(long Index);
	double GetOPCItemTimeStamp(long Index);
	void SetOPCItemData(long Index, const VARIANT& Value);
	BOOL GetOPCItemActive(long Index);
	CString GetOPCItemGroupName(long Index);
	void SetOPCItemGroupName(long Index, LPCTSTR Value);
	void OPCDeleteItem(long Index);
	void OPCItemActivateSuspend(long Index);
	VARIANT GetBytesPNG(long Compression);
	void SaveImageToPNG(LPCTSTR FileName, long Compression);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ITHERMOMETERX_H__DE87C81E_9774_43EF_BB37_1F3FF02A3A82__INCLUDED_)
